display_name: Your Site's Name Here
domainroot: http://micro.snook.pub/

forms:
  post_url: /
  combine_names: false
  submit_text: DO THE SIGN
  labels: true #false for placeholders

meta:
  title: Your Site's Name Here
  description: A description of your site. Relatively short is good. Use words
    that appear in your site. Like template repository shortcut helper library
    html sass bootstrap theme easy painless fun.
  keywords:
  fb_description:
  fb_site_name:
  fb_title:

footer:
  copyright: 2015 Organization. All rights reserved. Authorised by Jane Directorstenson, 555 Boulevard Rd, Suite 555, Springfield ST.
  mailto_subject: Here's a subject line about this campaign I'm supporting. Wee!
  twitter_message: "Tweet tweet! Come check out this cooooool campaign. http://micro.snook.pub/ #microsite @michaelsnook"

sass:
  sass_dir: scss

exclude:
  - Gruntfile.js
  - scss
  - .ruby-version
  - package.json
  - README.md
  - node_modules
  - bower_components
  - .sass-cache
  - CNAME
